name: dip
channels:
  - pytorch3d
  - iopath
  - fvcore
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py38h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20210915=py38
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - iopath=0.1.9=py38
  - jinja2=3.1.3=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h77fa898_7
  - libgomp=13.2.0=h77fa898_7
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.3.0=h4ab18f5_3
  - pillow=10.2.0=py38h5eee18b_0
  - pip=23.3.1=py38h06a4308_0
  - portalocker=2.8.2=py38h578d9bd_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - python_abi=3.8=2_cp38
  - pytorch=2.1.0=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.5=py38_cu118_pyt210
  - pyyaml=6.0.1=py38h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_1
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py38h06a4308_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.1.0=py38
  - torchvision=0.16.0=py38_cu118
  - typing_extensions=4.9.0=py38h06a4308_1
  - urllib3=2.1.0=py38h06a4308_1
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - blis==0.7.11
      - catalogue==2.0.10
      - chumpy==0.70
      - click==8.1.7
      - clip==1.0
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - configparser==7.0.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - cymem==2.0.8
      - decorator==4.4.2
      - en-core-web-sm==3.4.1
      - fonttools==4.51.0
      - freetype-py==2.4.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - imageio==2.34.0
      - imageio-ffmpeg==0.4.9
      - importlib-resources==6.4.0
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - langcodes==3.3.0
      - lazy-loader==0.4
      - lightning-utilities==0.11.2
      - matplotlib==3.1.3
      - mesh-to-sdf==0.0.15
      - moviepy==2.0.0.dev2
      - multidict==6.0.5
      - murmurhash==1.0.10
      - numpy==1.21.5
      - opencv-python==4.9.0.80
      - packaging==24.0
      - pandas==2.0.3
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - preshed==3.0.9
      - proglog==0.1.10
      - protobuf==5.27.0
      - pydantic==1.10.15
      - pyglet==2.1.dev2
      - pyopengl==3.1.0
      - pyparsing==3.1.2
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.8.4
      - pytz==2024.1
      - pywavelets==1.4.1
      - regex==2023.12.25
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.16.0
      - smart-open==6.4.0
      - smplx==0.1.28
      - spacy==3.4.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - tensorboardx==2.6.2.2
      - thinc==8.1.12
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - torchgeometry==0.1.2
      - torchmetrics==1.3.2
      - tqdm==4.66.2
      - transforms3d==0.4.1
      - trimesh==4.3.1
      - typer==0.4.2
      - tzdata==2024.1
      - wasabi==0.10.1
      - wcwidth==0.2.13
      - weasel==0.3.4
      - yarl==1.9.4
      - zipp==3.18.1
prefix: /home/gongjingyu/software/miniconda3/envs/omnicontrol
